# Generated by Django 6.0 on 2025-12-07 15:45

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE checkout_order ALTER COLUMN country TYPE varchar(40);"
        ),
    ]
