# Generated by Django 6.0 on 2025-12-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_order_country'),
    ]

    operations = [
         migrations.RunSQL(
            "ALTER TABLE checkout_order ALTER COLUMN country TYPE varchar(40);"
        ),
    ]
